console.log("hello! your learning console critter")
console.log("log things into the console like this ↓")
console.log(" console.log(your variable) ")
console.log("create a variable like this ↓")
console.log(" var name= value ")
console.log("use concat function to merge two variables")
console.log(" firststring.concat(secondstring) ")
console.log("find a square root like this ↓")
console.log(" Math.sqrt(number) ")